mockdeep/Rails-Template

- Gemfile
- Gemfile.lock
- README.md
Won't need most of these. For JSON serialization, we'll probably use a
more object-oriented solution than `jbuilder`.
> Deps: remove dependencies we likely won't use

- Gemfile
- Gemfile.lock
That's what `Gemfile.lock` is for. We leave the `rails` one locked,
though, since it's the entire backbone of our application. It's nice to
have informationally and we probably want to give it extra consideration
when upgrading.
> Deps: remove version contraints from Gemfile

- Gemfile
- Gemfile.lock
- README.md
`chromedriver-helper` [has been deprecated][1].
[1]: https://github.com/flavorjones/chromedriver-helper/issues/83
> Deps: use `webdrivers` gem

- .circleci/config.yml
CircleCI recommends pinning the OS version for build consistency.
Stretch is the latest and Jessie is end of life.
https://circleci.com/docs/2.0/circleci-images/#best-practices
> CI: specify stretch in CircleCI build image

- .circleci/config.yml
There is some hope that this will make builds faster as Postgres stores
in RAM instead of on disk.
https://circleci.com/docs/2.0/databases/#optimizing-postgres-images
> CI: enable ram postgres build on CircleCI

- .gitignore
- .rubocop.yml
- Gemfile
- Gemfile.lock
- app/channels/application_cable/channel.rb
- app/channels/application_cable/connection.rb
- app/controllers/application_controller.rb
- app/jobs/application_job.rb
- app/mailers/application_mailer.rb
- app/models/application_record.rb
- spec/channels/application_cable/channel_spec.rb
- spec/channels/application_cable/connection_spec.rb
- spec/controllers/application_controller_spec.rb
- spec/helpers/application_helper_spec.rb
- spec/jobs/application_job_spec.rb
- spec/mailers/application_mailer_spec.rb
- spec/models/application_record_spec.rb
- spec/spec_helper.rb
Built out simple files to test existing empty classes. I'm trying out a
test require strategy where we manually require files under test rather
than requiring `rails_helper` to pull in all of the Rails dependencies.
This should lead to faster individual test runs, though we'll see how
egregious it ends up being to add this to files.
> Specs: set up test coverage

- .rubocop.yml
- config/environments/development.rb
- config/environments/test.rb
- spec/support/capybara.rb
Puma had a noisy warning about header keys being invalid, and there was
another warning about Puma booting up when capybara first starts.
I also disabled the `Style/StringHashKeys` rule, as it wants to change
this. It's not a very safe rule for auto-correct, so probably best to
leave off.
> fix warnings from puma

- WISHLIST.md
- config/application.rb
When using `form_with` in Rails, it defaults to ajax submitting them.
The problem here is that the behavior is inconsistent when JS is enabled
or disabled. Flash messages don't display when JS is enabled, and there
needs to be a `.js.haml` template to update the page via JS if there is
any other update to be done. This causes some duplication between the
formats, so it would be nice to come up with a transparent way to make
both work with minimal duplication.
> Disable remote forms by default

- .circleci/config.yml
This will prevent non-JS tests from running against browsers. Right now
submitting forms results in different error flows depending on whether
we're running against `Rack::Test` or `Selenium`. I'd like to sync this
up at some point, but for now only tests with `js: true` will run
against a real browser.
> CircleCI: disable browser builds

- app/models/user.rb
- spec/models/user_spec.rb
This results in an unactionable `password_digest` message being
displayed to the user. `has_secure_password` already validates presence
of `password` and validates confirmation of `password_confirmation`.
> don't validate password_digest

- spec/rails_helper.rb
This will cause the views to be rendered and have at least a smoke test.
Beyond that we can also assert against what is rendered.
> RSpec: `render_views` for controller tests

- .rubocop.yml
`TargetRubyVersion` and `TargetRailsVersion` are automatically detected
by rubocop. `TargetRubyVersion` is [grabbed from `.ruby-version`][1] and
`TargetRailsVersion` [comes from `Gemfile.lock`][2]. Also, the `Rails`
setting is no longer necessary, as that is triggered by the fact that we
have a `require` line above for `rubocop-rails`.
[1]: https://github.com/rubocop-hq/rubocop/blob/HEAD@%7B2019-09-18T17:12:48Z%7D/manual/configuration.md#setting-the-target-ruby-version
[2]: https://github.com/rubocop-hq/rubocop-rails/blob/20586297d465867e7e19176a98e606516c6b81d3/config/default.yml#L6-L12
> Rubocop: remove unneeded settings from .rubocop.yml

- spec/support/capybara/rack_test.rb
- spec/support/matchers.rb
- spec/support/matchers/change_record.rb
- spec/support/matchers/delete_record.rb
- spec/support/matchers/have_error.rb
- spec/support/matchers/have_flash.rb
- spec/support/mocks.rb
Several matchers and some additional stuff for various purposes.
- `RackTest` doesn't implement the `accept_modal` method of other
drivers, so this adds it.
- `ChangeRecord` and `DeleteRecord` matchers implement common
expectations around `ActiveRecord`.
- `have_error` and `have_flash` encapsulate some feature expectations.
- `record_double` abstracts away a common testing use case where we want
to stub out some method on a record that is going to be found in the
controller like so:
```rb
user = User.create!(user_params)
expect(user).to receive(:destroy).and_return(false)
expect(User).to receive(:find).with(user.id).and_return(user)
session[:user_id] = user.id
```
Most of these are "just enough" to work for the time being, but will
probably need to be refined as new use cases pop up.
> RSpec: add a bunch of testing helpers

- app/controllers/accounts_controller.rb
- app/controllers/application_controller.rb
- app/controllers/welcome_controller.rb
For security, we're better defaulting to requiring the user to be logged
in and selectively disabling it where appropriate.
> default to authenticate user everywhere

- app/jobs/callable_job.rb
- spec/jobs/callable_job_spec.rb
`CallableJob` is a generic job that allows us to easily background any
class or constant that implements a `call` method without needing to
introduce a new type of job. This also makes zero downtime deploys
easier, since we don't need an extra step to introduce the new job
before adding any code that references it, though we still need to make
sure the callable is in production before adding any code that will
depend on it via `CallableJob`. This is less likely to be a problem,
however, since often times the logic that we want to background is
already in production and is slowing down the request lifecycle. We can
quickly change the logic to background it like so:
```diff
- MyThing.call(args)
+ CallableJob.perform_later("MyThing", args)
```
> introduce CallableJob

- config.ru
By default Ruby buffers to $stdout, which means output won't appear until a threshold has been reached.
This can make logging confusing because you won't see actions that have been performed immediately in the logs.
Setting sync to true tells Ruby to immediately flush all output.
> Sync standard out

- .rubocop.yml
- db/schema.rb
- Probably better not to wrap `schema.rb` methods in parens since its
format is pretty common.
- Also don't enforce the underscore format for `schema.rb` timestamp. It
reads more clearly with arbitrary positioning.
- Don't allow word array shorthand syntax. This is for the sake of
consistency. Rather than having a custom syntax for one particular
type of array, all arrays should look the same, as well as all
strings, for the most part.
> More rubocop updates

- config/application.rb
This check can cause N+1 queries when validating multiple records.
Instead we can validate the presence of a foreign key, rather than the
actual record. As long as there is a foreign key constraint in the
database it will end up being just as good without the performance
implications.
> Disable `belongs_to` default validation

- config/environments/development.rb
- config/environments/test.rb
Rather than silently swallowing errors, it'll help to have these fail
loudly.
> Raise on unpermitted params in dev/test mode

- .rubocop.yml
- app/views/accounts/new.html.haml
- app/views/accounts/show.html.haml
- Add a few more methods for `Style/MethodCallWithArgsParentheses`
- Disable `Style/CommentedKeyword`. I want to be able to add closing
comments to the `end` of some blocks, such as `class << self`.
- Switch `Style/StringLiteralsInInterpolation` to double quotes. Seems
like this should mirror `Style/StringLiterals`.
> Rubocop: configure more rules

- spec/rails_helper.rb
- spec/spec_helper.rb
- spec/support/capybara.rb
- spec/support/matchers.rb
It's a little easier to tell this way what order things are required in
for when there are order dependencies.
> Require individual files in rails_helper

- spec/support/webmock.rb
The `webdrivers` gem fetches browser drivers for system tests. WebMock
blocks these requests by default, so this allows them through.
> Allow geckodriver for Webmock

- Rakefile
This broke a production deploy because we've only got it in the dev/test
group in our Gemfile.
> Only load bundler audit task in dev/test modes

- .circleci/config.yml
This actually prevents merging security updates, since there might be
more than one security vulnerability at the same. When there are
multiple PRs to fix security issues, they individually fail because
`bundle audit` fails on the other dependency that is not being updated.
> CI: remove bundler audit check

- Gemfile
- Gemfile.lock
The latest version does not work with Capybara, yet.
> Deps: lock down puma version
