Gemfile
Don't anticipate needing ActionCable any time soon.
=> Deps: remove more deps we probably won't use

Gemfile, Gemfile.lock
We'll be wanting to do some authentication.
=> Deps: enable bcrypt

Gemfile
We can google gems we want to learn about.
=> Deps: remove comments from Gemfile

.circleci/config.yml, Gemfile, Gemfile.lock, README.md, app/controllers/application_controller.rb
[Brakeman][1] is a security scanner that helps us to avoid a variety of
security issues.
[1]: https://github.com/presidentbeef/brakeman
=> Deps: introduce Brakeman

README.md
=> remove todos from README

.circleci/config.yml, Gemfile, Gemfile.lock, Rakefile
Bundler Audit checks for security vulnerabilities in dependencies.
https://github.com/rubysec/bundler-audit
=> Security: add bundler-audit

.circleci/config.yml
No need to reference project name in CI config.
=> CI: make circle config generic

app/views/layouts/application.html.erb, config/application.rb, config/cable.yml, config/database.yml, config/environments/production.rb, package.json
Make it easy to `git grep -i yourappnamehere`.
=> generify naming throughout app

config/database.yml
Instead use user's credentials.
=> Dev: remove username and password from db config

Gemfile, Gemfile.lock
[`pry-rails`][1] to replace the Rails console and [`pry-byebug`][2] for
debugging tools.
[1]: https://github.com/rweng/pry-rails
[2]: https://github.com/deivid-rodriguez/pry-byebug
=> Console: add pry gems

Gemfile.lock
Forgot to update bundle on previous PR.
=> Deps: update Gemfile with pry-byebug

Gemfile, Gemfile.lock, bin/rspec, bin/spring
https://github.com/jonleighton/spring-commands-rspec
=> Add spring-commands-rspec

.rubocop.yml, Guardfile, app/models/user.rb, db/migrate/20190913200312_create_users.rb, db/schema.rb, spec/models/user_spec.rb
Plus some minor updates to rubocop/guard configurations
=> create user model

.rubocop.yml
These will be relevant for accounts stuff
=> add some additional rubocop configs

app/assets/stylesheets/application.scss
Also remove Sprockets directives
=> move `application.css` -> `application.scss`

app/assets/stylesheets/application.scss, app/controllers/accounts_controller.rb, app/controllers/application_controller.rb, app/views/accounts/new.html.haml, app/views/accounts/show.html.haml, app/views/layouts/application.html.haml, config/routes.rb, spec/controllers/accounts_controller_spec.rb, spec/system/account_spec.rb
- don't run non-js system tests on Firefox/Chrome
=> set up user accounts

Guardfile
In particular, I want it to keep failures so that when I save a file it
re-runs the tests that failed.
=> Guard: add a few options to RSpec in Guardfile

app/controllers/accounts_controller.rb, app/controllers/application_controller.rb
This allows us to better encapsulate the logic around modifying the
session and current user.
=> move log out logic to ApplicationController

app/controllers/application_controller.rb, app/models/nulls/null_user.rb, app/models/user.rb, app/views/layouts/application.html.haml, config/application.rb, spec/models/nulls/null_user_spec.rb, spec/models/user_spec.rb
Rather than checking on the presence of the user, we can instead check
methods on `NullUser`
=> introduce NullUser

Gemfile, Gemfile.lock, spec/spec_helper.rb, spec/support/vcr.rb
Set up a handful of stricter options, including ensuring that recording
doesn't happen on CI. I left a couple of options commented out for now
that I think we'll end up needing in the not too distant future.
=> introduce VCR and Webmock

yarn.lock
Got a security alert and dependabot can't seem to handle it.
=> Upgrade packages manually
